# Generated by Django 5.0.4 on 2024-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(default=None, upload_to='product_images', verbose_name='Изображение продукта'),
        ),
    ]
